-- UNO50 3.14 — catálogo oficial reformulado
UPDATE items SET is_active=FALSE;
INSERT INTO items(id,name,category,description,price,xp_required,rarity,asset,is_active) VALUES
('deck_classic','Baralho UNO50 Clássico','deck','Baralho padrão do UNO50.',0,0,'common','{"theme":"classic"}',TRUE),
('map_classroom','Sala de Aula','map','Mapa leve para partidas rápidas.',0,0,'common','{"theme":"classroom"}',TRUE),
('map_pirate','Navio Pirata','map','Mesa pirata com iluminação e clima de aventura.',1200,500,'epic','{"theme":"pirate"}',TRUE),
('map_saloon','Saloon Clássico','map','Taverna aconchegante para partidas.',800,250,'rare','{"theme":"saloon"}',TRUE),
('map_neon_city','Cidade Neon','map','Mesa urbana com luzes neon.',1600,1000,'epic','{"theme":"neon"}',TRUE),
('map_forest','Floresta UNO','map','Mesa natural com brilho suave.',900,350,'rare','{"theme":"forest"}',TRUE),
('map_desert','Deserto Dourado','map','Mesa quente com atmosfera dourada.',1000,450,'rare','{"theme":"desert"}',TRUE),
('map_ice','Montanha Congelada','map','Mesa gelada com efeitos azuis.',1400,800,'epic','{"theme":"ice"}',TRUE),
('map_space','Estação Espacial','map','Mesa futurista em órbita.',1800,1200,'legendary','{"theme":"space"}',TRUE),
('map_geometry','Laboratório UNO','map','Mapa futurista de treinamento.',700,150,'rare','{"theme":"geometry"}',TRUE),
('map_ceo','Dimensão CEO','map','Mapa reservado ao CEO.',0,0,'legendary','{"theme":"ceo","ceoOnly":true}',TRUE),
('hair_basic','Cabelo Clássico','hair','Visual inicial.',0,0,'common','{"style":"classic"}',TRUE),
('hair_curl','Cachos Modernos','hair','Cabelo volumoso e divertido.',1200,100,'common','{"style":"curl"}',TRUE),
('hair_long','Cabelo Longo','hair','Visual elegante.',1800,200,'rare','{"style":"long"}',TRUE),
('hair_mohawk','Moicano Neon','hair','Visual energético.',3200,500,'epic','{"style":"mohawk"}',TRUE),
('hair_afro','Afro Estiloso','hair','Volume e personalidade.',2200,250,'rare','{"style":"afro"}',TRUE),
('hair_braids','Tranças Urbanas','hair','Visual marcante.',2600,400,'rare','{"style":"braids"}',TRUE),
('hair_ice','Cabelo Gelo','hair','Brilho frio futurista.',5000,900,'epic','{"style":"ice"}',TRUE),
('hair_ceo','Cabelo CEO','hair','Visual exclusivo do CEO.',0,0,'legendary','{"style":"ceo","ceoOnly":true}',TRUE),
('shirt_basic','Camiseta UNO50','clothing','Roupa inicial.',0,0,'common','{"style":"basic"}',TRUE),
('shirt_red','Jaqueta Rubi','clothing','Jaqueta vermelha com acabamento brilhante.',1500,150,'common','{"style":"red"}',TRUE),
('shirt_neon','Jaqueta Neon','clothing','Roupa com identidade neon.',3500,500,'rare','{"style":"neon"}',TRUE),
('shirt_gold','Casaco Dourado','clothing','Visual dourado de prestígio.',7000,1000,'epic','{"style":"gold"}',TRUE),
('shirt_space','Traje Espacial','clothing','Roupa futurista.',9500,1500,'legendary','{"style":"space"}',TRUE),
('pants_basic','Calça Clássica','clothing','Roupa inicial.',0,0,'common','{"style":"basic"}',TRUE),
('pants_black','Calça Eclipse','clothing','Visual escuro elegante.',1000,100,'common','{"style":"black"}',TRUE),
('pants_neon','Calça Neon','clothing','Combina com a jaqueta neon.',2800,450,'rare','{"style":"neon"}',TRUE),
('shoes_basic','Tênis Clássico','clothing','Calçado inicial.',0,0,'common','{"style":"basic"}',TRUE),
('shoes_red','Tênis Rubi','clothing','Tênis vermelho esportivo.',1200,100,'common','{"style":"red"}',TRUE),
('shoes_gold','Botas Douradas','clothing','Botas de destaque.',6000,800,'epic','{"style":"gold"}',TRUE),
('glasses_basic','Óculos Clássicos','accessory','Óculos discretos.',700,50,'common','{"style":"basic"}',TRUE),
('glasses_cyan','Óculos Ciano','accessory','Lentes neon.',2200,250,'rare','{"style":"cyan"}',TRUE),
('glasses_gold','Óculos Dourados','accessory','Detalhe premium.',5000,600,'epic','{"style":"gold"}',TRUE),
('hat_cap','Boné Urbano','accessory','Boné casual.',900,100,'common','{"style":"hat_cap"}',TRUE),
('hat_cowboy','Chapéu do Capitão','accessory','Chapéu inspirado no mapa pirata.',4200,500,'rare','{"style":"hat_cowboy"}',TRUE),
('hat_crown','Coroa Lendária','accessory','Coroa para quem domina a mesa.',15000,2500,'legendary','{"style":"hat_crown"}',TRUE),
('backpack_blue','Mochila Ciano','accessory','Mochila compacta.',2500,300,'rare','{"style":"backpack_blue"}',TRUE),
('backpack_space','Mochila Orbital','accessory','Acessório futurista.',8000,1000,'epic','{"style":"backpack_space"}',TRUE),
('parrot_shoulder','Papagaio Companheiro','accessory','Companheiro cosmético de ombro.',10000,900,'epic','{"style":"parrot"}',TRUE),
('pirate_compass','Bússola do Capitão','accessory','Acessório temático pirata.',6500,600,'rare','{"style":"compass"}',TRUE),
('aura_blue','Aura Ciano','effect','Brilho azul suave.',3000,300,'rare','{"theme":"blue"}',TRUE),
('aura_gold','Aura Dourada','effect','Brilho dourado premium.',7500,1000,'epic','{"theme":"gold"}',TRUE),
('aura_rainbow','Aura Prisma','effect','Aura multicolorida.',12000,1800,'legendary','{"theme":"rainbow"}',TRUE),
('emote_wave','Aceno','emote','Emote inicial.',0,0,'common','{}',TRUE),
('emote_fire','Fogo','emote','Comemore uma jogada incrível.',2200,300,'rare','{}',TRUE),
('emote_dance','Dança da Vitória','emote','Animação de vitória.',6000,900,'epic','{}',TRUE),
('emote_cheer','Torcida','emote','Comemore com a mesa.',4000,500,'rare','{}',TRUE),
('title_beginner','INICIANTE','title','Emblema inicial.',0,0,'common','{}',TRUE),
('title_calculator','MESTRE DAS CARTAS','title','Emblema de veterano.',4500,700,'rare','{}',TRUE),
('title_master','LENDÁRIO','title','Emblema de alto nível.',11000,2500,'epic','{}',TRUE),
('title_ceo','DONO DO JOGO','title','Emblema administrativo exclusivo.',0,0,'legendary','{"ceoOnly":true}',TRUE)
ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,category=EXCLUDED.category,description=EXCLUDED.description,price=EXCLUDED.price,xp_required=EXCLUDED.xp_required,rarity=EXCLUDED.rarity,asset=EXCLUDED.asset,is_active=EXCLUDED.is_active;
INSERT INTO items(id,name,category,description,price,xp_required,rarity,asset,is_active) VALUES ('title_owner','DONO DO JOGO','title','Emblema exclusivo do CEO, com efeito lendário.',0,0,'mythic','{"ceoOnly":true,"effect":"owner"}',TRUE) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,rarity=EXCLUDED.rarity,asset=EXCLUDED.asset,is_active=EXCLUDED.is_active;
INSERT INTO achievements(id,name,description,icon,xp_reward,coin_reward) VALUES
('first_game','Primeira partida','Jogue sua primeira partida.','🎮',50,50),
('first_win','Primeira vitória','Vença uma partida.','🏆',100,100),
('ten_wins','10 vitórias','Alcance 10 vitórias.','👑',500,500),
('collector','Colecionador','Desbloqueie 10 itens cosméticos.','🎒',300,300)
ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,icon=EXCLUDED.icon,xp_reward=EXCLUDED.xp_reward,coin_reward=EXCLUDED.coin_reward;

